### PR TITLE
New recentering method

### PR DESCRIPTION
**Pull request by ElenaKoko**

### CODE REVIEW

**Comment by VChristiaens** [comment]
Looks good - thanks. I was just wondering: do you get errors if you uncomment lines 1153 to 1183? If not, these may be useful plots to keep.

**Comment by ElenaKoko** [comment]
> Looks good - thanks. I was just wondering: do you get errors if you uncomment lines 1153 to 1183? If not, these may be useful plots to keep.

It gives me errors, so i commented it out

**Comment by VChristiaens** [comment]
Ok, let's keep it like this then - the new centering method should take precedence over the other ones.
Can you also push your new parameter file in the Examples folder - to reflect the new recommended/default parameters, and add one line in VCAL_MANUAL_for_PREPROCESSING_IRDIS.txt to include the new centering method there too? Thanks!

**Comment by ElenaKoko** [comment]
> Ok, let's keep it like this then - the new centering method should take precedence over the other ones. Can you also push your new parameter file in the Examples folder - to reflect the new recommended/default parameters, and add one line in VCAL_MANUAL_for_PREPROCESSING_IRDIS.txt to include the new centering method there too? Thanks!

Will do!

**Comment by ElenaKoko** [comment]
> > Ok, let's keep it like this then - the new centering method should take precedence over the other ones. Can you also push your new parameter file in the Examples folder - to reflect the new recommended/default parameters, and add one line in VCAL_MANUAL_for_PREPROCESSING_IRDIS.txt to include the new centering method there too? Thanks!
> 
> Will do!

I get an error: hint: Updates were rejected because the remote contains work that you do not have locally. This is usually caused by another repository pushing to the same ref. You may want to first merge the remote changes (e.g., hint: 'git pull') before pushing again.
I think you need to accept the pull request first? I am not sure

**Comment by VChristiaens** [comment]
I think now you have to git pull, potentially solve conflicts, push again and submit another pull request

**Pull request merged**
